workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

variables:
  # Debugging facilities
  CI_DEBUG_TRACE: "true"
  # Access to Docker
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "${DOCKER_TLS_CERTDIR}/client"

stages:
  - build
  - release
  - deploy

docker-build-job:
  stage: build
  image: docker:24.0.5
  services:
      - name: docker:24.0.5-dind
        command: ["--mtu=1460"]
  script:
    - until docker info; do sleep 1; done
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - >-
        docker
        build
        --progress=plain
        --cache-from "${CI_REGISTRY_IMAGE}":latest
        --squash
        --pull
        --tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
        --file docker/Dockerfile
        .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"

docker-release-job:
  stage: release
  image: docker:24.0.5
  services:
      - name: docker:24.0.5-dind
        command: ["--mtu=1460"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - until docker info; do sleep 1; done
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - docker pull "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
    - VERSION="${CI_COMMIT_TAG#'release-'}"
    - VERSION_PATCH="${VERSION}"
    - VERSION_MINOR="${VERSION%.*}"
    - VERSION_MAJOR="${VERSION%.*.*}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${VERSION}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${VERSION_PATCH}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${VERSION_MINOR}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${VERSION_MAJOR}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - docker tag "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:latest"
    - docker push --all-tags "${CI_REGISTRY_IMAGE}"
    - docker logout